## Example Config file
BaseURL: "https://zglu.github.io"
#theme: "terminalcv"
title: "@zglu"
publishDir: "docs"

params:
  description: "Zhigang Lu's terminal page."
  prompt: "zglu@github.io"
  promptColor: yellow
# promptSimbols: ":~$"
# promptSimbolsColor: grey
# startxLocation: https://example.com
# hideSocialName: true
  exitLocation: 'about:blank'
  hidesource: true
  greeting: | 
    Hello there! This is Zhigang's terminal

    Type 'help' for a list of available commands


  about: 
      name: "Zhigang Lu"
      profession: "Bioinformatics Scientist"
      location: "DE"
      email: "zl at zlzyz.com"
#      homelink: "https://ZhigangLu.com"
      description: |
        Visionary Bioinformatics Leader with a Ph.D. in Biology and 11 years of deep expertise in computational biology, dedicated to leveraging large-scale NGS data, including 6 years in single-cell and 4 years in cutting-edge spatial omics analysis. Proven success over 3 years as a Bioinformatics Team Lead in the biotech industry, directing strategic initiatives across multiple international and interdisciplinary projects. High-impact scientific contributor with an h-index of 17, having authored and co-authored 20+ publications in top-tier journals including Science, Nature Communications, and Nucleic Acids Research. Technical expertise applied across key domains such as oncology, developmental biology, and clinical pathology.


  education:
   - courseName: Dr. rer. nat. in Biology
     color: green
     date: Sep 2015
     institution: JLU Giessen, Germany
     topic: Isolation, molecular characterisation, and comparative transcriptomics of S. mansoni gonads

  skills:
    - name: Linux & Bash 
      percentage: 90
      description: Classic and efficient for bioinformatics

    - name: R
      percentage: 85
      description: Seurat, SCE, ggplot2, dplyr, etc 

    - name: Python
      #color: blue
      percentage: 70
      description: Stereopy, scanpy, etc

    - name: NGS / bioinformatics
      percentage: 90
      description: Sequencing biodata


  languages:
    - name: Chinese
      percentage: 100
      #description: pasghettipigglywiggly

    - name: English
      #color: Blue
      percentage: 80
      description: The quick fox jumps over the lazy dog

    - name: German
      percentage: 60
      description: Naturwissenschaftler 


  social:
    ## IF you want to keep them aligned just add spaces
    - name: "Github"
      url: "          https://github.com/zglu"
    - name: "Twitter"
      url: "         https://twitter.com/zglu11"
    - name: "LinkedIn"
      url: "        https://www.linkedin.com/in/zhigang-lu3/"
    - name: "ORCID"
      url: "           https://orcid.org/0000-0001-6553-5944"
    - name: "ResearchGate"
      url: "    https://www.researchgate.net/profile/Zhigang_Lu3"
    - name: "Google Scholar"
      url: "  https://scholar.google.com/citations?hl=en&user=JGrDkIUAAAAJ"

  links:
    - name: "Single Cell Atlas"
      url: " https://zglu.notion.site/SingleCellAtlas-4a65b6b31295434295da0fa52e493a7a"
    - name: "Single Cell Tools"
      url: " https://zglu.notion.site/SingleCellTools-df629ab68c394329ae092c1d5225d174"


  experience:
    - jobTitle: Field Bioinformatics Specialist
      color: orange
      company: 'MGI Tech GmbH'
      location: Europe & Africa
      date: Dec 2024 - Present
      description: I managed Customer Success & Platform Adoption by providing specialized bioinformatics training and expert field support for advanced platforms (STOmics, MGI Single-Cell), significantly boosting technology use. I ensured Technical Pipeline Ownership through the hands-on setup, configuration, and debugging of critical bioinformatics pipelines and HPC accelerators (Ztron, MegaBolt). I was responsible for Large-Scale Data Delivery, encompassing the final analysis, interpretation, and communication of omics data to guarantee quality and customer insights. Finally, I served as the Strategic Cross-Functional Liaison, acting as the primary bioinformatics subject matter expert to bridge customers and internal teams (R&D, Product, Business) for complex troubleshooting and integrated solution delivery. 

    - jobTitle: Lead Bioinformatician (90% dry + 10% wet)
      color: orange
      company: 'BGI-Research / STOmics Tech' 
      location: Europe & Africa
      date: July 2022 - Nov 2024
      description: I managed and mentored a team of four bioinformaticians, overseeing technical training, data analysis, and customer support across the European region. This involved directing the end-to-end bioinformatics lifecycle for over 50 high-profile STOmics projects, including the management and delivery of 60+ Terabytes of Stereo-seq spatial data. I was also responsible for critical infrastructure and pipeline ownership, managing both local cluster and AWS Cloud environments, pipeline development, and data interpretation standards to guarantee reproducible, high-quality results. Furthermore, I acted as the Project Lead for external collaborations with top international laboratories, personally overseeing study design and analytical strategy, while establishing the team's pioneering expertise in over 20 single-cell and spatial multi-omics datasets.
      #textcolor: grey

    - jobTitle: Bioinformatics Consultant (100% dry)
      color: orange
      company: 'freelance'
      location: Germany 
      date: Feb 2021  - Jun 2022
      description: I delivered expert advisory and strategic analysis to international research groups, focusing on high-level consulting and strategic planning for complex NGS projects. My role included advanced, hands-on data processing for specialized datasets, such as single-cell transcriptomics, Visium spatial transcriptomics, and advanced comparative transcriptomics. Crucially, I drove methodology innovation by developing and applying novel machine learning and data modeling methods to extract key insights from this complex analytical data.

    - jobTitle: PostDoc / Computational Biologist (70% dry + 30% wet)
      color: orange
      company: 'Wellcome Sanger Institute'
      location: UK
      date: Mar 2017 - Jan 2021
      description: My focus centered on Specialized Single-Cell & Genomics, where I drove research using advanced sequencing data across genomics, transcriptomics, and epigenetics, with specific expertise in Single-cell RNA-seq analysis. I was responsible for Pipeline & Resource Development, creating critical bioinformatics tools to improve genome assembly and annotation (for Schistosoma mansoni), while also establishing resources like data integration, visualization tools, and the web portal development platform, Schisto.xyz. Furthermore, I contributed to Methodological Innovation by applying modeling and machine learning techniques to extract insights from complex RNA-Seq and ChIP-Seq datasets.

    - jobTitle: PostDoc Researcher (40% dry + 60% wet)
      color: orange
      company: 'JLU Giessen'
      location: Germany
      date: Oct 2015 - Feb 2017
      description: I effectively demonstrated Molecular Benchwork Integration by combining bioinformatics with essential molecular characterization techniques, including organ/cell isolation, gene/protein expression, and imaging. My role involved Full-Cycle Omics Management, where I directed the entire workflow for large-scale comparative transcriptomics, spanning both the molecular/wet lab execution (library preparation and QC) and the computational strategy (quantification and Bioconductor analysis), ultimately culminating in the design and deployment of a functional data web portal.


  projects:
    - title: (DataViz) OmicsEE -- omics expression explorer
      date: since 2024
      link: https://github.com/zglu/OmicsEE
      description: Fast gene expression exploration across multiple datasets and/or modalities, in any species. No installation needed

    - title: (DataViz) Schistosome gene expression database
      date: since 2018
      link: https://schisto.xyz
      description: Bulk, scRNA-seq and spatial gene expression database for S. mansoni

    - title: (Coding) Gene functional enrichment analysis
      date: 2021
      link: https://github.com/zglu/Gene-function-enrichment
      description: Enrichment test using GO, Pfam, InterPro, or KEGG Pathway annotations

    - title: (Fun) Interactive charting / slides
      #color: blueviolet
      date: 2017
      link: https://ivis.netlify.app/
      description: Javascript-based tool for interactive plotting and html slides

  publications:
    - title: The retinoic acid family-like nuclear receptor SmRAR identified by single-cell transcriptomics of ovarian cells controls oocyte differentiation in Schistosoma mansoni
      year: 2024
      link: https://doi.org/10.1093/nar/gkae1228
      journal: Nucleic Acids Research 

    - title: The stage-and sex-specific transcriptome of the human parasite Schistosoma mansoni
      year: 2023
      link: https://doi.org/10.1038/s41597-023-02674-2
      journal: Sci. Data

    - title: Single-cell atlas of the first intra-mammalian developmental stage of the human parasite Schistosoma mansoni
      year: 2020
      link: https://www.nature.com/articles/s41467-020-20092-5
      journal: Nat. Commun

    - title: Large-scale RNAi screening uncovers therapeutic targets in the parasite Schistosoma mansoni
      year: 2020
      link: https://www.science.org/doi/10.1126/science.abb7699
      journal: Science
      #description: contributed to bioinformatics analysis

    - title: A web portal for gene expression across all life stages of Schistosoma mansoni
      year: 2018
      link: https://doi.org/10.1101/308213
      journal: bioRxiv
 
    - title: A gene expression atlas of adult Schistosoma mansoni and their gonads
      year: 2017
      link: https://www.nature.com/articles/sdata2017118
      journal: Sci. Data
 
    - title: Schistosome sex matters a deep view into gonad-specific and pairing-dependent transcriptomes reveals a complex gender interplay
      year: 2016
      link: https://www.nature.com/articles/srep31150
      journal: Sci. Rep.
      description: featured in Science Editor's Choice
 
#  certifications:
#  - certName: Example Cert
#    company: Example Certifying Company
#    date: Date of Completion
#    #description: Lorem Ipsum
  
  misc: 
    commandName: more
    title: "Copyright 2025 @zglu"
    titleColor: paleturquoise
    content: |
          Built with Hugo terminalcv and jQuery Terminal

    contentColor: blue
