## Example Config file
BaseURL: "https://zglu.github.io"
#theme: "terminalcv"
title: "@zglu"
publishDir: "docs"

params:
  description: "Zhigang Lu's terminal page."
  prompt: "zglu@github.io"
  promptColor: yellow
# promptSimbols: ":~$"
# promptSimbolsColor: grey
# startxLocation: https://example.com
# hideSocialName: true
  exitLocation: 'about:blank'
  hidesource: true
  greeting: | 
    Hello there!

    Type 'help' for a list of available commands


  about: 
      name: "Zhigang Lu"
      profession: "Bioinformatics Scientist"
      location: "DE"
#      email: "foo@someemail.com"
      homelink: "https://ZhigangLu.com"
      description: |
              I am a molecular and computational biologist broadly interested in gene expression and regulation, functional genomics, and drug targets discovery. I work on multi-layered omics data (genomics, transcriptomics, epigenomics, single-cell and spatial transcriptomics). I also apply machine learning modelling and do large dataset visualisation (eg. web-sharing). 

              Topics include NGS, single-cell and spatial multi-omics, parasites, cancer research, data science


  social:
    ## IF you want to keep them aligned just add spaces
    - name: "Github"
      url: "          https://github.com/zglu"
    - name: "Twitter"
      url: "         https://twitter.com/zglu11"
    - name: "Linkedin"
      url: "        https://www.linkedin.com/in/zhigang-lu3/"
    - name: "ResearchGate"
      url: "    https://www.researchgate.net/profile/Zhigang_Lu3"
    - name: "Google Scholar"
      url: "  https://scholar.google.com/citations?hl=en&user=JGrDkIUAAAAJ"

  links:
    - name: "Single Cell Atlas"
      url: " https://zglu.notion.site/SingleCellAtlas-4a65b6b31295434295da0fa52e493a7a?pvs=25"
    - name: "Single Cell Tools"
      url: " https://zglu.notion.site/SingleCellTools-df629ab68c394329ae092c1d5225d174"

  experience:
    - jobTitle: Senior Bioinformatics Scientist
      color: orange
      company: 'BGI-Research' 
      location: Europe & Africa
      date: July 2022 - Present
      description: Single-cell and spatial multi-omics; cancer research; development

    - jobTitle: Data Scientist/Bioinformatician
      color: orange
      company: 'external'
      location: Germany 
      date: Feb 2021  - Jun 2022
      description: Project conception, bioinformatics analysis, scRNA-seq data analysis

    - jobTitle: Computational Biologist
      color: orange
      company: 'Wellcome Sanger Institute'
      location: Hinxton, UK
      date: Mar 2017 - Jan 2021
      description: Genome assembly and annotation, omics data analysis and integration, bioinformatics, machine learning modelling, data portal development

    - jobTitle: PostDoc Researcher
      color: orange
      company: 'JLU Giessen'
      location: Germany
      date: Oct 2015 - Feb 2017
      description: Single cell preparation and sequencing (scRNA-seq); data integration and visualisation


  education:
   - courseName: Dr. rer. nat in Biology
     color: green
     date: Sep 2015
     institution: JLU Giessen
     topic: Isolation, molecular characterisation, and comparative transcriptomics of S. mansoni reproductive organs


  skills:
    - name: Linux & Bash 
      percentage: 90
      description: Classic and efficient

    - name: R
      percentage: 80
      description: Seurat, SCE, ggplot2, dplyr, etc 

    - name: Python
      #color: blue
      percentage: 70
      description: Stereopy, scanpy, etc

    - name: NGS / bioinformatics
      percentage: 90
      description: Sequencing biodata


  languages:
    - name: English
      #color: Blue
      percentage: 80
      description: The quick fox jumps over the lazy dog

    - name: Chinese
      percentage: 100
      #description: pasghettipigglywiggly

    - name: German
      percentage: 50
      description: Naturwissenschaftler 


  projects:
    - title: (DataViz) Schistosome gene expression database
      color: purple
      date: since 2018
      link: http://schisto.xyz
      description: RNA-seq based gene expression data for S. mansoni

    - title: (Coding) Gene functional enrichment analysis
      color: purple
      date: 2021
      link: https://github.com/zglu/Gene-function-enrichment
      description: Enrichment test using GO, Pfam, InterPro, or KEGG Pathway annotations

    - title: (Fun) Interactive charting / slides
      color: purple
      date: 2017
      link: https://ivis.netlify.app/
      description: Javascript-based tool for interactive plotting and html slides

  publications:
    - title: Daily rhythms in gene expression of the human parasite Schistosoma mansoni
      year: 2021
      link: doi:10.1186/s12915-021-01189-9
      journal: BMC Biol.

    - title: Large-scale RNAi screening uncovers therapeutic targets in the parasite Schistosoma mansoni
      year: 2020
      link: https://www.science.org/doi/10.1126/science.abb7699
      journal: Science
      #description: contributed to bioinformatics analysis


#  certifications:
#  - certName: Example Cert
#    company: Example Certifying Company
#    date: Date of Completion
#    #description: Lorem Ipsum
  
  misc: 
    commandName: more
    title: "Copyright 2023 @zglu"
    titleColor: teal
    content: |
          Built with terminalcv and jQuery Terminal

    contentColor: blue
