## Example Config file
BaseURL: "https://zglu.github.io"
#theme: "terminalcv"
title: "@zglu"
publishDir: "docs"

params:
  description: "Zhigang Lu's terminal page."
  prompt: "zglu@github.io"
  promptColor: yellow
# promptSimbols: ":~$"
# promptSimbolsColor: grey
# startxLocation: https://example.com
# hideSocialName: true
  exitLocation: 'about:blank'
  hidesource: true
  greeting: | 
    Hello there! This is Zhigang's terminal

    Type 'help' for a list of available commands


  about: 
      name: "Zhigang Lu"
      profession: "Bioinformatics Scientist"
      location: "DE"
#      email: "foo@someemail.com"
#      homelink: "https://ZhigangLu.com"
      description: |
              I am a molecular and computational biologist broadly interested in gene expression and regulation, functional genomics, and drug targets discovery. I work on multi-layered omics data (genomics, transcriptomics, epigenomics, single-cell and spatial transcriptomics), apply machine learning modelling and do large dataset visualisation (eg. web-sharing). 

              Knowledge and years of experience in NGS, single-cell and spatial multi-omics, bioinformatics, and parasite biology. Currently work in cancer research.


  education:
   - courseName: Dr. rer. nat. in Biology
     color: green
     date: Sep 2015
     institution: JLU Giessen, Germany
     topic: Isolation, molecular characterisation, and comparative transcriptomics of S. mansoni gonads

  skills:
    - name: Linux & Bash 
      percentage: 90
      description: Classic and efficient for bioinformatics

    - name: R
      percentage: 80
      description: Seurat, SCE, ggplot2, dplyr, etc 

    - name: Python
      #color: blue
      percentage: 70
      description: Stereopy, scanpy, etc

    - name: NGS / bioinformatics
      percentage: 90
      description: Sequencing biodata


  languages:
    - name: English
      #color: Blue
      percentage: 80
      description: The quick fox jumps over the lazy dog

    - name: Chinese
      percentage: 100
      #description: pasghettipigglywiggly

    - name: German
      percentage: 60
      description: Naturwissenschaftler 


  social:
    ## IF you want to keep them aligned just add spaces
    - name: "Github"
      url: "          https://github.com/zglu"
    - name: "Twitter"
      url: "         https://twitter.com/zglu11"
    - name: "LinkedIn"
      url: "        https://www.linkedin.com/in/zhigang-lu3/"
    - name: "ORCID"
      url: "           https://orcid.org/0000-0001-6553-5944"
    - name: "ResearchGate"
      url: "    https://www.researchgate.net/profile/Zhigang_Lu3"
    - name: "Google Scholar"
      url: "  https://scholar.google.com/citations?hl=en&user=JGrDkIUAAAAJ"

  links:
    - name: "Single Cell Atlas"
      url: " https://zglu.notion.site/SingleCellAtlas-4a65b6b31295434295da0fa52e493a7a"
    - name: "Single Cell Tools"
      url: " https://zglu.notion.site/SingleCellTools-df629ab68c394329ae092c1d5225d174"


  experience:
    - jobTitle: Project Leader & Lead Bioinformatician (90% dry + 10% wet)
      color: orange
      company: 'BGI-Research' 
      location: Europe & Africa
      date: July 2022 - Present
      description: Single-cell and spatial multi-omics; cancer research; high-resolution spatial profiling
      #textcolor: grey

    - jobTitle: Bioinformatics Consultant (100% dry)
      color: orange
      company: 'freelance'
      location: Germany 
      date: Feb 2021  - Jun 2022
      description: Project conception, bioinformatics analysis, scRNA-seq data analysis

    - jobTitle: PostDoc / Computational Biologist (70% dry + 30% wet)
      color: orange
      company: 'Wellcome Sanger Institute'
      location: UK
      date: Mar 2017 - Jan 2021
      description: Single-cell RNA-seq, genome assembly and annotation, omics data analysis and integration, bioinformatics, machine learning modelling, data portal development

    - jobTitle: PostDoc Researcher (40% dry + 60% wet)
      color: orange
      company: 'JLU Giessen'
      location: Germany
      date: Oct 2015 - Feb 2017
      description: Single cell preparation and sequencing (scRNA-seq); data integration and visualisation


  projects:
    - title: (DataViz) Schistosome gene expression database
      date: since 2018
      link: http://schisto.xyz
      description: RNA-seq gene expression data for S. mansoni

    - title: (Coding) Gene functional enrichment analysis
      date: 2021
      link: https://github.com/zglu/Gene-function-enrichment
      description: Enrichment test using GO, Pfam, InterPro, or KEGG Pathway annotations

    - title: (Fun) Interactive charting / slides
      #color: blueviolet
      date: 2017
      link: https://ivis.netlify.app/
      description: Javascript-based tool for interactive plotting and html slides

  publications:
    - title: The stage-and sex-specific transcriptome of the human parasite Schistosoma mansoni
      year: 2023
      link: https://doi.org/10.1101/2023.05.02.539039
      journal: bioRxiv

    - title: Single-cell atlas of the first intra-mammalian developmental stage of the human parasite Schistosoma mansoni
      year: 2020
      link: https://www.nature.com/articles/s41467-020-20092-5
      journal: Nat. Commun

    - title: Large-scale RNAi screening uncovers therapeutic targets in the parasite Schistosoma mansoni
      year: 2020
      link: https://www.science.org/doi/10.1126/science.abb7699
      journal: Science
      #description: contributed to bioinformatics analysis

    - title: A web portal for gene expression across all life stages of Schistosoma mansoni
      year: 2018
      link: https://doi.org/10.1101/308213
      journal: bioRxiv
 
    - title: A gene expression atlas of adult Schistosoma mansoni and their gonads
      year: 2017
      link: https://www.nature.com/articles/sdata2017118
      journal: Sci. Data
 
    - title: Schistosome sex matters a deep view into gonad-specific and pairing-dependent transcriptomes reveals a complex gender interplay
      year: 2016
      link: https://www.nature.com/articles/srep31150
      journal: Sci. Rep.
      description: featured in Science Editor's Choice
 
#  certifications:
#  - certName: Example Cert
#    company: Example Certifying Company
#    date: Date of Completion
#    #description: Lorem Ipsum
  
  misc: 
    commandName: more
    title: "Copyright 2023 @zglu"
    titleColor: paleturquoise
    content: |
          Built with Hugo terminalcv and jQuery Terminal

    contentColor: blue
